repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
          - click>=8.1
          - pyzotero>=1.5
          - rich>=13.0
          - platformdirs>=4.0
          - markdownify>=1.2.2
        pass_filenames: false
        entry: mypy src/zotero_cli_cc/
